[package]
name = "timecard"
version = "0.1.0"
authors = ["Samuel J Vanderwaal <samuel.vanderwaal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
chrono = "0.4.10"
diesel = { version = "1.4.3", features = ["sqlite"] }
serde = { version = "1.0.103", features = ["derive"] }
dotenv = "0.15.0"
lazy_static = "1.4.0"
